//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocated
    {
        public int allocated_id { get; set; }
        public string user_id { get; set; }
        public int room_no { get; set; }
    
        public virtual UserDb UserDb { get; set; }
        public virtual Room Room { get; set; }
    }
}
