//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int complaint_id { get; set; }
        public string user_id { get; set; }
        public string complaint_subject { get; set; }
        public string complaint_descrip { get; set; }
        public System.DateTime complaint_date { get; set; }
        public string complaint_status { get; set; }
    
        public virtual UserDb UserDb { get; set; }
    }
}
