//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int expense_id { get; set; }
        public string user_id { get; set; }
        public string expense_descrip { get; set; }
        public decimal expense_money { get; set; }
        public System.DateTime expense_date { get; set; }
        public string expense_status { get; set; }
    
        public virtual UserDb UserDb { get; set; }
    }
}
