//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities22 : DbContext
    {
        public Database1Entities22()
            : base("name=Database1Entities22")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allocated> Allocateds { get; set; }
        public virtual DbSet<Canteen> Canteens { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<Hostel> Hostels { get; set; }
        public virtual DbSet<Laundry> Laundries { get; set; }
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<LoginDb> LoginDbs { get; set; }
        public virtual DbSet<MessMenu> MessMenus { get; set; }
        public virtual DbSet<Notice> Notices { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Penalty> Penalties { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Take> Takes { get; set; }
        public virtual DbSet<User_Canteen> User_Canteen { get; set; }
        public virtual DbSet<UserDb> UserDbs { get; set; }
        public virtual DbSet<GatePass> GatePasses { get; set; }
    }
}
