//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hostel
    {
        public int hostel_id { get; set; }
        public string hostel_name { get; set; }
        public int no_of_rooms { get; set; }
        public int no_of_floors { get; set; }
        public int no_of_beds { get; set; }
    }
}
