//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessMenu
    {
        public int menu_id { get; set; }
        public string menu { get; set; }
        public System.DateTime date { get; set; }
        public string menu_type { get; set; }
    }
}
