//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int notice_id { get; set; }
        public string notice_sub { get; set; }
        public string notice_descrip { get; set; }
        public System.DateTime notice_date { get; set; }
    }
}
