//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        public int penalty_id { get; set; }
        public string user_id { get; set; }
        public string penalty_subject { get; set; }
        public string penalty_descrip { get; set; }
        public decimal penalty_money { get; set; }
        public System.DateTime penalty_date { get; set; }
        public string penalty_status { get; set; }
    
        public virtual UserDb UserDb { get; set; }
    }
}
