//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Canteen
    {
        public int user_canteen_id { get; set; }
        public string user_id { get; set; }
        public int item_id { get; set; }
        public int quantity { get; set; }
        public System.DateTime canteen_date { get; set; }
        public string canteen_status { get; set; }
    
        public virtual Canteen Canteen { get; set; }
        public virtual UserDb UserDb { get; set; }
    }
}
